// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.12.0+8c27801dc8d42ccc00997f25c0b8f45f8d4a233e
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace BCSample.Events
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("avrogen", "1.12.0+8c27801dc8d42ccc00997f25c0b8f45f8d4a233e")]
	public partial class LoginActionEvent : global::Avro.Specific.ISpecificRecord
	{
		public static global::Avro.Schema _SCHEMA = global::Avro.Schema.Parse(@"{""type"":""record"",""name"":""LoginActionEvent"",""namespace"":""BCSample.Events"",""fields"":[{""name"":""Username"",""type"":""string""},{""name"":""LoginTime"",""type"":""string""},{""name"":""IpAddress"",""default"":"""",""type"":""string""},{""name"":""UserAgent"",""default"":"""",""type"":""string""}]}");
		private string _Username;
		private string _LoginTime;
		private string _IpAddress;
		private string _UserAgent;
		public virtual global::Avro.Schema Schema
		{
			get
			{
				return LoginActionEvent._SCHEMA;
			}
		}
		public string Username
		{
			get
			{
				return this._Username;
			}
			set
			{
				this._Username = value;
			}
		}
		public string LoginTime
		{
			get
			{
				return this._LoginTime;
			}
			set
			{
				this._LoginTime = value;
			}
		}
		public string IpAddress
		{
			get
			{
				return this._IpAddress;
			}
			set
			{
				this._IpAddress = value;
			}
		}
		public string UserAgent
		{
			get
			{
				return this._UserAgent;
			}
			set
			{
				this._UserAgent = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.Username;
			case 1: return this.LoginTime;
			case 2: return this.IpAddress;
			case 3: return this.UserAgent;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.Username = (System.String)fieldValue; break;
			case 1: this.LoginTime = (System.String)fieldValue; break;
			case 2: this.IpAddress = (System.String)fieldValue; break;
			case 3: this.UserAgent = (System.String)fieldValue; break;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
